apiVersion: v1
kind: PersistentVolume
metadata:
  name: cloudai-druid-pv
  labels:
    cloudai-pvname: cloudai-druid-pv
spec:    
  capacity:       
    storage: 3Gi   
  accessModes:   
    - ReadWriteMany   
  hostPath:
    path: /k8s/cloudai-2/druid
  persistentVolumeReclaimPolicy: Recycle
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloudai-druid-pvc
  namespace: cloudai-2
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      cloudai-pvname: cloudai-druid-pv
  resources:
    requests:
      storage: 3Gi

