apiVersion: v1
kind: Service
metadata:
  name: druid-historical
  namespace: cloudai-2
  labels:
    component: historical
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: historical
