apiVersion: v1
kind: Service
metadata:
  name: kylin-ui
  namespace: cloudai-2
  labels:
    version: kylin-2.6.1
    app: kylin
spec:
  ports:
    - port: 7070
      targetPort: 7070
      nodePort: 31210
  selector:
    app: kylin
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: kylin
  namespace: cloudai-2
  labels:
    version: kylin-2.6.1
    app: kylin
spec:
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    app: kylin
  clusterIP: "None" 
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kylin
  namespace: cloudai-2
  labels:
    version: kylin-2.6.1
    app: kylin
spec:
  serviceName: kylin
  replicas: 3
  selector:
    matchLabels:
      app: kylin
  template:
    metadata:
      labels:
        version: kylin-2.6.1
        app: kylin
    spec:
      affinity:
        podAntiAffinity:    # 尽量不要分配在一起
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app:  kylin

      containers:
        - name: kylin
          image: luanpeng/lp:hadoop-2.7.3-hbase-1.3.1-hive-2.3.4-spark-2.4.0-kelin-2.6.1
#          imagePullPolicy: Always # Always #IfNotPresent
          workingDir: /usr/local/kylin    # 
          command: ["/bin/bash","/tmp/kylin-config/bootstrap.sh"]
          ports:
            - containerPort: 7070
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
          env:
            - name: MAX_SERVERS
              value: "3"
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
          - name: kylin-config
            mountPath: /tmp/kylin-config
          - name: hadoop-config
            mountPath: /tmp/hadoop-config
          - name: hive-config
            mountPath: /tmp/hive-config
          - name: hbase-config
            mountPath: /tmp/hbase-config
          - name: spark-config
            mountPath: /tmp/spark-config
          readinessProbe:
            httpGet:
              path: /kylin
              port: 7070
            initialDelaySeconds: 30
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /kylin
              port: 7070
            initialDelaySeconds: 300
            timeoutSeconds: 2
      volumes:
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: hadoop-config
        configMap:
          name: hadoop-configmap
      - name: hive-config
        configMap:
          name: hive-configmap
      - name: hbase-config
        configMap:
          name: hbase-configmap
      - name: kylin-config
        configMap:
          name: kylin-configmap
      - name: spark-config
        configMap:
          name: spark-configmap
